
// Code generated by go generate; DO NOT EDIT.
// using data from templates/templates
package templates

func TemplatesMap() map[string]string {
    templatesMap := make(map[string]string)

templatesMap["main.go.tmpl"] = `package main

import (
	"fmt"
	"github.com/olegsu/openc"
)

func main() {

	meta := openc.PipelineMetadata{
		Name: "Hello World",
	}

	spec := openc.PipelineSpec{
		Tasks: []openc.Task{
			openc.Task{
					Metadata: openc.TaskMetadata{
						Name: "echo",
					},
					Spec: openc.TaskSpec{
						Condition: []openc.Condition{
							openc.Condition{
								Name: "on",
								Func: func(ev *openc.Event, state *openc.State) bool {
									return ev.Metadata.Name == "engine.started"
								},
							},
						},
						Reusable: true,
						Command:  "echo",
						Arguments: []openc.Argument{
							openc.Argument{
								Name:  "Echo",
								Value: fmt.Sprintf("Running task echo"),
							},
						},
					},
				},
		},
	}
	p := openc.Pipeline{
		Metadata: meta,
		Spec:     spec,
	}

	e := openc.NewEngine(&openc.EngineOptions{
		Pipeline:          p,
		WriteStateToFile:  "./logs/state.yaml",
		TaskLogsDirectory: "./logs",
	})
	_ = e.Run()
}` 

    return  templatesMap
}
